In [1]:
import numpy as np
import pandas as pd

**Pivot Tables**

In [5]:
data = {
    'Date':pd.date_range('2026-06-21', periods=20),
    'Product': ['A','B','C','D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
           'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep Month Quarter
0  2026-06-21       A   East    868     15   John  June      Q2
1  2026-06-22       B   West    278     18   Mary  June      Q2
2  2026-06-23       C  North    839     93    Bob  June      Q2
3  2026-06-24       D  South    751     86  Alice  June      Q2
4  2026-06-25       A   East    542     25   John  June      Q2
5  2026-06-26       B   West    873     86   Mary  June      Q2
6  2026-06-27       C  North    820     27    Bob  June      Q2
7  2026-06-28       D  South    477     15  Alice  June      Q2
8  2026-06-29       A   East    220     86   John  June      Q2
9  2026-06-30       B   West    616     24   Mary  June      Q2
10 2026-07-01       C  North    126     93    Bob  July      Q3
11 2026-07-02       D  South    504     56  Alice  July      Q3
12 2026-07-03       A   East    317     37   John  July      Q3
13 2026-07-04       B   West    790     16   Mary  July      Q3
14 2026-07-05       C  North    632     62    Bob  July      Q3
15 2026-07-06       D  South    340     41  Alice  July      Q3
16 2026-07-07       A   East    849     15   John  July      Q3
17 2026-07-08       B   West    291     64   Mary  July      Q3
18 2026-07-09       C  North    253     75    Bob  July      Q3
19 2026-07-10       D  South    694     72  Alice  July      Q3

In [11]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product", aggfunc="median")

Product      A      B      C      D
Region
East     542.0    NaN    NaN    NaN
North      NaN    NaN  632.0    NaN
South      NaN    NaN    NaN  504.0
West       NaN  616.0    NaN    NaN

In [12]:
pt = pd.pivot_table(df,values=['Sales','Units'],index="Region",columns="Product")
pt

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     559.2    NaN    NaN    NaN  35.6   NaN   NaN   NaN
North      NaN    NaN  534.0    NaN   NaN   NaN  70.0   NaN
South      NaN    NaN    NaN  553.2   NaN   NaN   NaN  54.0
West       NaN  569.6    NaN    NaN   NaN  41.6   NaN   NaN

**Cross Table**

In [14]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [16]:
pd.crosstab(df['Rep'],df['Quarter'])

Quarter  Q2  Q3
Rep
Alice     2   3
Bob       2   3
John      3   2
Mary      3   2

In [17]:
pd.crosstab(df['Month'], df['Product'])

Product  A  B  C  D
Month
July     2  2  3  3
June     3  3  2  2